tapirgrocer/config/routes.rb
Rails.application.routes.draw do
  get 'linkgen/index'

  get 'link/index'

  get 'link_generator/index'

  resources :sign_ups
  resources :entries
  root to: "sign_ups#new"

  get 'panel/:id', to: 'panel#index', as: 'panel'
  get 'entries/', to: 'entries#index', as: 'all_entries'
  get 'link/', to: 'link#index', as: 'link'
  # root to: "entries#index"
end

tapirgrocer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tapirgrocer/app/models/entry.rb
class Entry < ApplicationRecord
end

tapirgrocer/app/models/sign_up.rb
class SignUp < ApplicationRecord
end

tapirgrocer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tapirgrocer/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Check-in was successful, enjoy shopping at Tapir Grocer!' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:fullname, :nric, :body_temp)
    end
end

tapirgrocer/app/controllers/link_controller.rb
class LinkController < ApplicationController
  require 'rqrcode'
  def index
    @qr = RQRCode::QRCode.new("http://tahmidrahman.com/taprigrocer/app/views/entries/new")
    # @qr = RQRCode::QRCode.new("http://localhost:3000/taprigrocer/app/views/entries/new")
# With default options specified explicitly

  end 
end

tapirgrocer/app/controllers/panel_controller.rb
class PanelController < ApplicationController
  def index
  end
end

tapirgrocer/app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  before_action :set_sign_up, only: [:show, :edit, :update, :destroy]

  # GET /sign_ups
  # GET /sign_ups.json
  def index
    @sign_ups = SignUp.all
  end

  # GET /sign_ups/1
  # GET /sign_ups/1.json
  def show
  end

  # GET /sign_ups/new
  def new
    @sign_up = SignUp.new
  end

  def panel
    @panel= SignUp.panel
  end
  # GET /sign_ups/1/edit
  def edit
  end

  # POST /sign_ups
  # POST /sign_ups.json
  def create
    @sign_up = SignUp.new(sign_up_params)

    respond_to do |format|
      if @sign_up.save
        # format.html { redirect_to @sign_up, notice: 'Sign up was successfully created.' }
        format.html { redirect_to panel_path(1)}
      else
        format.html { render :new }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_ups/1
  # PATCH/PUT /sign_ups/1.json
  def update
    respond_to do |format|
      if @sign_up.update(sign_up_params)
        format.html { redirect_to @sign_up, notice: 'Sign up was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up }
      else
        format.html { render :edit }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_ups/1
  # DELETE /sign_ups/1.json
  def destroy
    @sign_up.destroy
    respond_to do |format|
      format.html { redirect_to sign_ups_url, notice: 'Sign up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up
      @sign_up = SignUp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sign_up_params
      params.require(:sign_up).permit(:fullname, :store_location)
    end
end

tapirgrocer/app/helpers/application_helper.rb
module ApplicationHelper
end

tapirgrocer/app/helpers/entries_helper.rb
module EntriesHelper
end

tapirgrocer/app/helpers/link_generator_helper.rb
module LinkGeneratorHelper
end

tapirgrocer/app/helpers/link_helper.rb
module LinkHelper
end

tapirgrocer/app/helpers/linkgen_helper.rb
module LinkgenHelper
end

tapirgrocer/app/helpers/panel_helper.rb
module PanelHelper
end

tapirgrocer/app/helpers/sign_ups_helper.rb
module SignUpsHelper
end

tapirgrocer/app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class ="message is-danger">
      <div class = "message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class ="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="card">
      <div class="card-content">
        <div class="field">
          <%= form.label :"Full Name", class: "label is-capitalized"%>
          <%= form.text_field :fullname, class: "input is-rounded", type: "text", placeholder: "Enter your full name", id: :entry_fullname %>
        </div>

        <div class="field">
          <%= form.label :"NRIC", class: "label is-uppercase"%>
          <%= form.number_field :nric, class: "input is-rounded", type: "text", placeholder: "Enter your NRIC number", id: :entry_nric %>
        </div>

        <div class="field">
          <%= form.label :"Body Temperature", class: "label is-capitalized"%>
          <%= form.number_field :body_temp, class: "input is-rounded", type: "text", placeholder: "Enter your body temperature", id: :entry_body_temp %>
        </div>

        <div class="actions">
          <%= form.submit class: "button is-success is-rounded " %>
        </div>
    </div>
  </div>
<% end %>

tapirgrocer/app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">   
    <div class="column is-one-third">
        <div class="card">
            <div class="card-content">
                <h1 class = "is-size-2 has-text-weight-bold mb-3">Edit Entry</h1>
            </div>
        </div>
        <%= render 'form', entry: @entry %>
    </div>
</div>

tapirgrocer/app/views/entries/index.html.erb
<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class ="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.fullname %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class = "has-text-weight-bold">NRIC: </span><%= entry.nric %></p>
            <p><span class = "has-text-weight-bold">Body Temperature: </span><%= entry.body_temp %>°C</p>
            <p><span class = "has-text-weight-bold">Date: </span><%= entry.created_at.to_s(:nice_date) %></p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: "card-footer-item" %>
          <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

tapirgrocer/app/views/entries/new.html.erb
<div class="columns is-centered mt-6">   
    <div class="column is-one-third">
        <div class="card">
           <header class="card-header">
                <h1 class = "is-size-2 has-text-weight-bold has-text-centered">Check-in</h1>
            </header>
        </div>
        <%= render 'form', entry: @entry %>
    </div>
</div>

tapirgrocer/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @entry.fullname %>
</p>

<p>
  <strong>NRIC:</strong>
  <%= @entry.nric %>
</p>

<p>
  <strong>Body Temperature:</strong>
  <%= @entry.body_temp %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

tapirgrocer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tapir Grocer</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render "shared/header" %>
    <% if notice.present?%>
      <div class="notification is-link is-light"><%= notice %></p>
    <% end %>
    <% if alert.present?%>
      <div class="notification is-danger is-light"><%= alert %></p>
    <% end %>
    <div class ="container">
      <%= yield %>
    </div>
  </body>
</html>

tapirgrocer/app/views/link/index.html.erb
<div class="columns mt-6 is-centered">
    <div class ="column is-one-third">
        <div class="card">
            <header class="card-header">
                <h1 class = "is-size-2 has-text-weight-bold">Customer Check-in</h1>
            </header>
            <div class="card-content">
                <%= raw @qr.as_html %>
            </div>
        </div>
    </div>
</div>

tapirgrocer/app/views/panel/index.html.erb
<div class="columns mt-6 is-centered">
    <div class ="column is-one-third">
        <div class="card">
            <header class="card-header">
                <p class = "card-header-title">Welcome</p><%# //TO DO: Add name %>
            </header>
            <div class="card-content">
                <div class="field has-text-centered">
                    <%= link_to"Check-in Link", link_url, class: "button is-success is-rounded" %>
                </div>
                <div class="field has-text-centered">
                    <%= link_to"Check-in Records", all_entries_url, class: "button is-success is-rounded" %>
                </div>
            </div>
        </div>
    </div>
</div>

tapirgrocer/app/views/shared/_header.html.erb
<section class="hero is-light is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <div class="navbar-item">
            <svg fill ="#000000" id="Capa_1" enable-background="new 0 0 512.006 512.006" height="25" viewBox="0 0 512.006 512.006" width="25" xmlns="http://www.w3.org/2000/svg"><g><path d="m15 61.003h35.277c6.592 0 12.363 4.233 14.326 10.532l82.359 263.844c-15.287 7.198-25.962 22.638-25.962 40.624 0 24.814 20.186 44.99 45 44.99h17.763c-1.681 4.715-2.763 9.726-2.763 15.01 0 24.814 20.186 45 45 45s45-20.186 45-45c0-5.284-1.082-10.295-2.763-15.01h65.526c-1.681 4.715-2.763 9.716-2.763 15 0 24.814 20.186 45.01 45 45.01s45-20.186 45-45c0-5.284-1.082-10.285-2.763-15h17.763c8.291 0 15-6.709 15-15s-6.709-15-15-15h-270c-8.262 0-15-6.724-15-15s6.738-15 15-15h247.562c20.684 0 38.643-14.019 43.682-34.087l54.316-217.28c1.113-4.482.117-9.229-2.725-12.861-2.842-3.647-7.207-5.771-11.836-5.771h-394.895l-8.848-28.418c-5.918-18.896-23.203-31.582-42.979-31.582h-35.277c-8.291 0-15 6.709-15 15s6.709 14.999 15 14.999zm317.76 270h-63.52l-11.25-90h86.019zm56.48-210h88.541l-22.5 90h-77.291zm-15 120h73.541l-19.658 78.633c-1.67 6.694-7.646 11.367-14.561 11.367h-50.572zm-15.23-120-11.25 90h-93.52l-11.25-90zm-120 210h-61.965l-28.099-90h78.814zm-26.25-210 11.25 90h-84.432l-28.099-90z"/></g></svg>
            <span class = "has-text-weight-bold is-size-4 ml-4">Tapir Grocer</span>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>

tapirgrocer/app/views/sign_ups/_form.html.erb
<%= form_with(model: sign_up, local: true) do |form| %>
  <% if sign_up.errors.any? %>
    <div class ="message is-danger">
      <div class = "message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class ="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div class="card">
  <div class="card-content">
    <div class="field">
      <%= form.label :"Full Name", class: "label is-capitalized"%>
      <%= form.text_field :fullname, class: "input is-rounded", type: "text", placeholder: "Enter your full name", id: :sign_up_fullname %>
    </div>
    <div class="field">
      <%= form.label :"Store Location", class: "label is-capitalized"%>
      <%= form.text_field :store_location, class: "input is-rounded", type: "text", placeholder: "Enter your current store location", id: :sign_up_store_location %>
    </div>
    <div class="actions">
      <%= form.submit class: "button is-success is-rounded " %>
    </div>
  </div>
</div>
<% end %>

tapirgrocer/app/views/sign_ups/edit.html.erb
<div class="columns is-centered mt-6">   
    <div class="column is-one-third">
        <div class="card">
            <div class="card-content">
                <h1 class = "is-size-2 has-text-weight-bold mb-3">Edit Sign Up</h1>
            </div>
        </div>
        <%= render 'form', sign_up: @sign_up %>
    </div>
</div>

tapirgrocer/app/views/sign_ups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign Ups</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Store location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_ups.each do |sign_up| %>
      <tr>
        <td><%= sign_up.fullname %></td>
        <td><%= sign_up.store_location %></td>
        <td><%= link_to 'Show', sign_up %></td>
        <td><%= link_to 'Edit', edit_sign_up_path(sign_up) %></td>
        <td><%= link_to 'Destroy', sign_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign Up', new_sign_up_path %>

tapirgrocer/app/views/sign_ups/new.html.erb
<div class="columns is-centered mt-6 sign-up">   
    <div class="column is-one-third">
        <div class="card">
            <div class="card-content">
                <h1 class = "is-size-1 has-text-weight-bold mb-3">Sign up</h1>
            </div>
        </div>
        <%= render 'form', sign_up: @sign_up %>
    </div>
</div>

tapirgrocer/app/views/sign_ups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @sign_up.fullname %>
</p>

<p>
  <strong>Store Location:</strong>
  <%= @sign_up.store_location %>
</p>

<%= link_to 'Edit', edit_sign_up_path(@sign_up) %> |
<%= link_to 'Back', sign_ups_path %>